### ISSUE TITLE
Problems with no-named data

### ISSUE THREAD

**Issue by Harmanz** [dicksonlaw583/jsontoolkit#1]
How should i get from such json values for xp and gold
    "reward":
    {
        "random_amount":
        {
            "amounts":
            [
                { "xp": 35.0, "gold": 50.0 },
                { "xp": 45.0, "gold": 30.0 },
                { "xp": 50.0, "gold": 24.0 }
            ]
        }
}
when i am trying to use json_get(json,"reward","random_amount","amounts","xp");
i am getting 45 value, but how can i get value for next xp?

**Comment by dicksonlaw583** [comment]
You have a list under `"amounts"` and forgot to index that.
```
json_get(json, "reward", "random_amount", "amounts", 1, "xp")
```
Vary the `1` above and you can get at the others in the same list.

**Comment by Harmanz** [comment]
Thank you very much
