### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Harmanz** [dicksonlaw583/jsontoolkit#4]
Excuse me, for writing this here.

You did great job with your extension, and really helped dumbs as i am to works with jsons.

But it would be just perfect, if you'll make some function that would allow to set new keys with one string, even if its not created yet. Something like

json_set(path_part_1,path_part_2,path_part_3,path_part_4,key,value);

**Comment by Harmanz** [comment]
To explain my problem better:  your extension doesnt gives me enough automation

For example, i need to operate object that linked to different json path sizes. So i made such script, that uses array with path elements, via your functions. Because i need to preset path somewhere, and use script that not depends of path size

```
/// @param jsconstruct
/// @param path_array
var Source=argument1;
var PA=argument2;
var Length=array_length_1d(PA);

#region zero length error
if(Length<1)
{
	show_message("json_get_ext: empty path array");
	return(undefined);
}
#endregion
#region define value to set in json
var Value;
if(Source.DataType=="real")
{
	if(!is_char_in_string(".",Source.String))
		Value=real(Source.String+".0");
	else
		Value=real(Source.String);
}
if(Source.DataType=="int")
{
	Value="I"+Source.String+"I";
}
if(Source.DataType=="str")
{
	Value=Source.String;
}
if(Source.DataType=="bool")
{
	Value="bool_"+Source.String;
}
if(Source.DataType=="boolean")
Value="bool_"+Value;
#endregion

#macro pa1 PA[0]
#macro pa2 PA[0],PA[1]
#macro pa3 PA[0],PA[1],PA[2]
#macro pa4 PA[0],PA[1],PA[2],PA[3]
#macro pa5 PA[0],PA[1],PA[2],PA[3],PA[4]
#macro pa6 PA[0],PA[1],PA[2],PA[3],PA[4],PA[5]
#macro pa7 PA[0],PA[1],PA[2],PA[3],PA[4],PA[5],PA[6]
#macro pa8 PA[0],PA[1],PA[2],PA[3],PA[4],PA[5],PA[6],PA[7]
#macro pa9 PA[0],PA[1],PA[2],PA[3],PA[4],PA[5],PA[6],PA[7],PA[8]
#macro pa10 PA[0],PA[1],PA[2],PA[3],PA[4],PA[5],PA[6],PA[7],PA[8],PA[9]

#region set json depenging on path array size
if(Length==1)
	return( json_set(argument0,pa1,Value) );
if(Length==2)
	return( json_set(argument0,pa2,Value) );
if(Length==3)
	return( json_set(argument0,pa3,Value) );
if(Length==4)
	return( json_set(argument0,pa4,Value) );
if(Length==5)
	return( json_set(argument0,pa5,Value) );
if(Length==6)
	return( json_set(argument0,pa6,Value) );
if(Length==7)
	return( json_set(argument0,pa7,Value) );
if(Length==8)
	return( json_set(argument0,pa8,Value) );
if(Length==9)
	return( json_set(argument0,pa9,Value) );
if(Length==10)
	return( json_set(argument0,pa10,Value) );
#endregion

```

**Comment by Harmanz** [comment]
But this script doesnt works if some part of path doesnt exists. And i cant make same script for insert_nested, because it contains structure function instead of simple path

**Comment by dicksonlaw583** [comment]
Do you mean something like this, where parts of the path are defined by arrays and can thus be manipulated at runtime?
```
{
  "data": {
    "names": [
      { "name": "Allan", "hp": 23 },
      { "name": "Barbara", "hp": 45 }
    ]
  }
}
```
```
json_set(map, ["data", "names", 0, "name"], "Alice");
var datapath = ["names", 0];
json_set(map, "data", datapath, "name", "Bob");
```
If that's the case, I can implement this alongside the planned addition of negative index numbers for lists.

But if you mean creating substructures for paths that don't already exist (e.g. `json_set(map, "data", "some_other_data", 0, "xp", 67);` for the data sample above), that's not something I'm willing to do. There are just too many poorly defined and unsafe behaviours to support in the general case, for example when a map already exists at a position but a list index is specified (e.g. `json_set(map, "data", 0, "newdata");`) or vice versa (e.g. `json_set(map, "data", "names", "foo", "newdata");`), or when `undefined` or negative list indexes (when they become supported) appear in the inexistent portions (e.g. `json_set(map, "some_other_data", undefined, -2, "new_data");`). You are free to create your own script that does the automatic insertions the way you prefer, but I won't support it in the main library.

**Comment by Harmanz** [comment]
i meant substructures for paths that don't already exist, but using arrays in path would be great too, thank you

**Comment by Harmanz** [comment]
sorry for bothering you again. i just want to say that i made such script as i asked you. it requires only array with path and creates all unexisent elements in it. script supports only lists-in-maps, maps-in-lists, maps-in-maps , but not lists-in-lists now, i will make it later. I think this is very useful (at least for me) so you can add something like this to your extension if you want

///@param structure
///@param path_array
```
///@param path_element

var OriginalStructure=argument0;
var PathArray=argument1;
var ArraySize=array_length_1d(PathArray);
var PathElement=argument2;
var IShouldCreate="map";



if(PathElement==(ArraySize-1))
	IShouldCreate="value";
else if(is_number(PathArray[PathElement+1]))
	IShouldCreate="list";


#region List 
if(ds_exists(argument0,ds_type_list))
{
	var ListNum=real(PathArray[PathElement]);
	if(IShouldCreate=="map")
	{
		var map;
		while(ds_list_size(argument0)<=ListNum)
		{
			ds_list_add(argument0,ds_map_create());
			var LS=ds_list_size(argument0);
			ds_list_mark_as_map(argument0,LS-1);

		}
		json_create_structure(argument0[|ListNum],PathArray,PathElement+1);
	}
	
}
#endregion
#region Map
else if(ds_exists(argument0,ds_type_map))
{
	
	if(IShouldCreate=="map")
	{
		if(!ds_map_exists(argument0,PathArray[PathElement]))
			ds_map_add_map(argument0,PathArray[PathElement],ds_map_create());
		json_create_structure(ds_map_find_value(argument0,PathArray[PathElement]),PathArray,PathElement+1);
	}
	
	if(IShouldCreate=="list")
	{
		if(!ds_map_exists(argument0,PathArray[PathElement]))
			ds_map_add_list(argument0,PathArray[PathElement],ds_list_create());
		json_create_structure(ds_map_find_value(argument0,PathArray[PathElement]),PathArray,PathElement+1);
	}
	
	if(IShouldCreate=="value")
		if(!ds_map_exists(argument0,PathArray[PathElement]))
			ds_map_add(argument0,PathArray[PathElement],0);
}
#endregion


```

**Comment by dicksonlaw583** [comment]
The v1.1.0 update includes support for array-specified paths.
